### ISSUE TITLE
Collaborator (and PAUSE co-maint)?

### ISSUE THREAD

**Issue by mohawk2** [PDLPorters/PDL-Graphics-Prima#34]
I'd like this module (and its ::Drawing counterpart) to be up to date. If you'd like help on this, I'd be happy to offer it if you could add me as collaborator on the repo and co-maint on PAUSE (my ID: `ETJ`). Also a superb candidate would be @zmughal (PAUSE: `ZMUGHAL`).

As a stretch-goal, you might even transfer the repo to PDLPorters and first-come to me or Zaki, if you're not doing Perl stuff any more?

Likewise, I believe you have other PDL modules on GitHub and/or CPAN that I'd love to see up to date on CPAN, and would love to help with those too.

**Comment by dk** [comment]
#metoo

**Comment by run4flat** [comment]
FYI, I'm going to try to hand these off some time next week. Sorry it took so long to reach that conclusion. :-/

**Comment by run4flat** [comment]
For the record here, I have sent an email directly to both of you to discuss ownership or co-maint on a number of my projects. This issue will be closed as soon as we move those conversations forward.

**Comment by dk** [comment]
Can you resend? I cant seem to find anything. Or discussing here is equally fine for me

**Comment by dk** [comment]
Ah see now nevermind
