### ISSUE TITLE
Deprecated Prima module.

### ISSUE THREAD

**Issue by aero** [PDLPorters/PDL-Graphics-Prima#35]
Hi,
I got the following messages during installation.
```
.
.
Running Build test for DCMERTENS/PDL-Graphics-Prima-0.17.tar.gz
Warning: Prima::ImageDialog is deprecated. Use Prima::Dialog::ImageDialog instead
Warning: Prima::FileDialog is deprecated. Use Prima::Dialog::FileDialog instead
# Testing PDL::Graphics::Prima 0.17, Perl 5.032001, C:\strawberry-perl-5.32-64bit\perl\bin\perl.exe
t\00-load-main.t .... ok
Warning: Prima::ImageDialog is deprecated. Use Prima::Dialog::ImageDialog instead
Warning: Prima::FileDialog is deprecated. Use Prima::Dialog::FileDialog instead
# Testing PDL::Graphics::Prima::Simple, Perl 5.032001, C:\strawberry-perl-5.32-64bit\perl\bin\perl.exe
t\01-load-simple.t .. ok
Warning: Prima::ImageDialog is deprecated. Use Prima::Dialog::ImageDialog instead
Warning: Prima::FileDialog is deprecated. Use Prima::Dialog::FileDialog instead
t\200-binning.t ..... ok
.
.
```

There are no such module files(Prima::FileDialog, Prima::ImageDialog) with clean install the latest Prima module.
So I copied previous Prima module files for temporary fix.
Please patch them.

**Comment by run4flat** [comment]
Thanks @aero! Your solution will work for now. I have fixed this in the latest version on github, but there are some other things I was in the middle of. I'll look over things soon (this weekend?) and see if I can push the existing development version as-is, so at least the CPAN version works again. I'll leave this ticket open until I've made that decision.

**Comment by mohawk2** [comment]
Please do release the latest! :-)

**Comment by mohawk2** [comment]
Since this is patched, I will close this. Thank you for the report! A new release will come out soon, with various other fixes and improvements.
