### ISSUE TITLE
PDF output is different from EPS output

### ISSUE THREAD

**Issue by zmughal** [PDLPorters/PDL-Graphics-Prima#41]
See <https://github.com/PDLPorters/PDL-Graphics-Prima/pull/40#issuecomment-1368103603>.

**Comment by mohawk2** [comment]
@dk Your help here would be greatly appreciated!

**Comment by dk** [comment]
#42 addresses this ( and more ) but I'm afraid github botched the PR. Do tell if it is okay as is or needs to be redone

**Comment by mohawk2** [comment]
@zmughal Does #43 sort this? If so, please close :-) (I'll put out a new release soon)

**Comment by zmughal** [comment]
Looks good! Fixed by <https://github.com/PDLPorters/PDL-Graphics-Prima/pull/43>. Thanks @dk!

![image](https://user-images.githubusercontent.com/94489/211722997-ac02d0a1-d233-4d7a-ac0e-336918d5e02f.png)
